package com.example.common.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.common.dao.GdUser;

import com.example.common.dao.GdUserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gdUserDaoConfig;

    private final GdUserDao gdUserDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gdUserDaoConfig = daoConfigMap.get(GdUserDao.class).clone();
        gdUserDaoConfig.initIdentityScope(type);

        gdUserDao = new GdUserDao(gdUserDaoConfig, this);

        registerDao(GdUser.class, gdUserDao);
    }
    
    public void clear() {
        gdUserDaoConfig.clearIdentityScope();
    }

    public GdUserDao getGdUserDao() {
        return gdUserDao;
    }

}
